from enum import Enum, unique


#     PASSPORT, NATIONAL_ID_CARD, DRIVER_LICENSE, MILITARY_ID, GREEN_CARD, TRAVEL_DOCUMENT, ALIEN_REGISTRATION_CARD, BIRTH_CERTIFICATE, OTHERS
@unique
class PassengerIdType(Enum):

    PASSPORT = "PASSPORT"
    NATIONAL_ID_CARD = "NATIONAL_ID_CARD"
    DRIVER_LICENSE = "DRIVER_LICENSE"
    MILITARY_ID = "MILITARY_ID"
    GREEN_CARD = "GREEN_CARD"
    TRAVEL_DOCUMENT = "TRAVEL_DOCUMENT"
    ALIEN_REGISTRATION_CARD = "ALIEN_REGISTRATION_CARD"
    BIRTH_CERTIFICATE = "BIRTH_CERTIFICATE"
    OTHERS = "OTHERS"

    def to_ams_dict(self):
        return self.name
