import json
from com.alipay.ams.api.model.result import Result
from com.alipay.ams.api.model.amount import Amount
from com.alipay.ams.api.model.amount import Amount
from com.alipay.ams.api.model.amount import Amount
from com.alipay.ams.api.model.amount import Amount
from com.alipay.ams.api.model.amount import Amount
from com.alipay.ams.api.model.amount import Amount
from com.alipay.ams.api.model.payment_method import PaymentMethod
from com.alipay.ams.api.model.invoice_shipping import InvoiceShipping
from com.alipay.ams.api.model.invoice_item import InvoiceItem
from com.alipay.ams.api.model.invoice_payment import InvoicePayment
from com.alipay.ams.api.model.invoice_note import InvoiceNote
from com.alipay.ams.api.model.billing_discount import BillingDiscount
from com.alipay.ams.api.model.amount import Amount
from com.alipay.ams.api.model.amount import Amount
from com.alipay.ams.api.model.amount import Amount



from com.alipay.ams.api.response.alipay_response import AlipayResponse

class AlipayInvoiceInquireDetailsResponse(AlipayResponse):
    def __init__(self, rsp_body):
        super(AlipayResponse, self).__init__() 

        self.__result = None  # type: Result
        self.__invoice_id = None  # type: str
        self.__invoice_request_id = None  # type: str
        self.__subscription_id = None  # type: str
        self.__customer_id = None  # type: str
        self.__invoice_number = None  # type: str
        self.__customer_first_name = None  # type: str
        self.__customer_last_name = None  # type: str
        self.__customer_email = None  # type: str
        self.__reason = None  # type: str
        self.__phase_no = None  # type: str
        self.__status = None  # type: str
        self.__currency = None  # type: str
        self.__subtotal = None  # type: Amount
        self.__discount_amount = None  # type: Amount
        self.__total_amount = None  # type: Amount
        self.__paid_amount = None  # type: Amount
        self.__remain_amount = None  # type: Amount
        self.__tax_amount = None  # type: Amount
        self.__collection_method = None  # type: str
        self.__payment_method = None  # type: PaymentMethod
        self.__shipping = None  # type: InvoiceShipping
        self.__hosted_invoice_url = None  # type: str
        self.__period_start = None  # type: str
        self.__period_end = None  # type: str
        self.__due_date = None  # type: str
        self.__paid_time = None  # type: str
        self.__description = None  # type: str
        self.__items = None  # type: [InvoiceItem]
        self.__payments = None  # type: [InvoicePayment]
        self.__invoice_notes = None  # type: [InvoiceNote]
        self.__gmt_create = None  # type: str
        self.__gmt_update = None  # type: str
        self.__discounts = None  # type: [BillingDiscount]
        self.__post_payment_credit_notes_amount = None  # type: Amount
        self.__pre_payment_credit_notes_amount = None  # type: Amount
        self.__payment_deducted = None  # type: Amount
        self.parse_rsp_body(rsp_body) 


    @property
    def result(self):
        """Gets the result of this AlipayInvoiceInquireDetailsResponse.
        
        """
        return self.__result

    @result.setter
    def result(self, value):
        self.__result = value
    @property
    def invoice_id(self):
        """
        System-generated invoice ID. Cannot be null. Returned only when result.resultCode is SUCCESS.
        """
        return self.__invoice_id

    @invoice_id.setter
    def invoice_id(self, value):
        self.__invoice_id = value
    @property
    def invoice_request_id(self):
        """
        Merchant-supplied idempotency key (echo-back from creation). Cannot be null. Returned only when result.resultCode is SUCCESS.
        """
        return self.__invoice_request_id

    @invoice_request_id.setter
    def invoice_request_id(self, value):
        self.__invoice_request_id = value
    @property
    def subscription_id(self):
        """
        Associated subscription ID. Omitted for standalone manual invoices (invoices not linked to a subscription). Returned only when result.resultCode is SUCCESS.
        """
        return self.__subscription_id

    @subscription_id.setter
    def subscription_id(self, value):
        self.__subscription_id = value
    @property
    def customer_id(self):
        """
        Customer ID this invoice belongs to. Cannot be null. Returned only when result.resultCode is SUCCESS.
        """
        return self.__customer_id

    @customer_id.setter
    def customer_id(self, value):
        self.__customer_id = value
    @property
    def invoice_number(self):
        """
        Human-readable sequential invoice number, unique per merchant (e.g., &#x60;INV-0001&#x60;). Generated by &#x60;InvoiceNumberSequenceService&#x60; at creation time. Suitable for display on PDFs and customer-facing pages. Cannot be null. Returned only when result.resultCode is SUCCESS.
        """
        return self.__invoice_number

    @invoice_number.setter
    def invoice_number(self, value):
        self.__invoice_number = value
    @property
    def customer_first_name(self):
        """
        Customer&#39;s first name. Populated from the customer record at invoice creation time. PII - see the six-element PII disclosure below the table. Omitted when not set on the customer record. Returned only when result.resultCode is SUCCESS.
        """
        return self.__customer_first_name

    @customer_first_name.setter
    def customer_first_name(self, value):
        self.__customer_first_name = value
    @property
    def customer_last_name(self):
        """
        Customer&#39;s last name. Populated from the customer record at invoice creation time. PII - see the six-element PII disclosure below the table. Omitted when not set on the customer record. Returned only when result.resultCode is SUCCESS.
        """
        return self.__customer_last_name

    @customer_last_name.setter
    def customer_last_name(self, value):
        self.__customer_last_name = value
    @property
    def customer_email(self):
        """
        Customer&#39;s email address. Populated from the customer record at invoice creation time. PII - see the six-element PII disclosure below the table. Omitted when not set on the customer record. Returned only when result.resultCode is SUCCESS.
        """
        return self.__customer_email

    @customer_email.setter
    def customer_email(self, value):
        self.__customer_email = value
    @property
    def reason(self):
        """
        Invoice creation reason: &#x60;MANUAL&#x60;, &#x60;SUBSCRIPTION_CREATION&#x60;, &#x60;SUBSCRIPTION_RECURRENCE&#x60;, &#x60;SUBSCRIPTION_UPDATE&#x60;. Cannot be null. Returned only when result.resultCode is SUCCESS.
        """
        return self.__reason

    @reason.setter
    def reason(self, value):
        self.__reason = value
    @property
    def phase_no(self):
        """
        Subscription phase number. Identifies which billing phase generated this invoice. Value range: 1-unlimited. Returned only for subscription-generated invoices (&#x60;reason&#x60; !&#x3D; &#x60;MANUAL&#x60;); omitted for manual invoices. Returned only when result.resultCode is SUCCESS.
        """
        return self.__phase_no

    @phase_no.setter
    def phase_no(self, value):
        self.__phase_no = value
    @property
    def status(self):
        """
        Current invoice status: &#x60;DRAFT&#x60;, &#x60;OPEN&#x60;, &#x60;PAID&#x60;, &#x60;UNCOLLECTIBLE&#x60;, &#x60;VOID&#x60;. Cannot be null. Returned only when result.resultCode is SUCCESS.
        """
        return self.__status

    @status.setter
    def status(self, value):
        self.__status = value
    @property
    def currency(self):
        """
        Three-letter ISO currency code in uppercase (e.g., &#x60;\&quot;USD\&quot;&#x60;). The invoice currency. All &#x60;Amount.currency&#x60; sub-fields within this response echo the same uppercase code. Cannot be null. Returned only when result.resultCode is SUCCESS.
        """
        return self.__currency

    @currency.setter
    def currency(self, value):
        self.__currency = value
    @property
    def subtotal(self):
        """Gets the subtotal of this AlipayInvoiceInquireDetailsResponse.
        
        """
        return self.__subtotal

    @subtotal.setter
    def subtotal(self, value):
        self.__subtotal = value
    @property
    def discount_amount(self):
        """Gets the discount_amount of this AlipayInvoiceInquireDetailsResponse.
        
        """
        return self.__discount_amount

    @discount_amount.setter
    def discount_amount(self, value):
        self.__discount_amount = value
    @property
    def total_amount(self):
        """Gets the total_amount of this AlipayInvoiceInquireDetailsResponse.
        
        """
        return self.__total_amount

    @total_amount.setter
    def total_amount(self, value):
        self.__total_amount = value
    @property
    def paid_amount(self):
        """Gets the paid_amount of this AlipayInvoiceInquireDetailsResponse.
        
        """
        return self.__paid_amount

    @paid_amount.setter
    def paid_amount(self, value):
        self.__paid_amount = value
    @property
    def remain_amount(self):
        """Gets the remain_amount of this AlipayInvoiceInquireDetailsResponse.
        
        """
        return self.__remain_amount

    @remain_amount.setter
    def remain_amount(self, value):
        self.__remain_amount = value
    @property
    def tax_amount(self):
        """Gets the tax_amount of this AlipayInvoiceInquireDetailsResponse.
        
        """
        return self.__tax_amount

    @tax_amount.setter
    def tax_amount(self, value):
        self.__tax_amount = value
    @property
    def collection_method(self):
        """
        Payment collection method. Allowed values: &#x60;CHARGE_AUTOMATICALLY&#x60; - automatically charge the customer&#39;s default payment method when the invoice is finalized; &#x60;SEND_INVOICE&#x60; - send the invoice to the customer for manual payment via email. Cannot be null. Returned only when result.resultCode is SUCCESS.
        """
        return self.__collection_method

    @collection_method.setter
    def collection_method(self, value):
        self.__collection_method = value
    @property
    def payment_method(self):
        """Gets the payment_method of this AlipayInvoiceInquireDetailsResponse.
        
        """
        return self.__payment_method

    @payment_method.setter
    def payment_method(self, value):
        self.__payment_method = value
    @property
    def shipping(self):
        """Gets the shipping of this AlipayInvoiceInquireDetailsResponse.
        
        """
        return self.__shipping

    @shipping.setter
    def shipping(self, value):
        self.__shipping = value
    @property
    def hosted_invoice_url(self):
        """
        URL to the invoice hosted page where the merchant/customer can view, download, or pay the invoice. The URL carries an opaque signed view token - it does not expose the raw &#x60;invoiceId&#x60; or &#x60;merchantId&#x60;. Links expire per the view-link validity period (see the &#x60;createViewLink&#x60; API) and are invalidated when the invoice is voided. Returned when: (1) invoice is OPEN (auto-generated during finalization), or (2) invoice is DRAFT and a view link was created via &#x60;createViewLink&#x60; API. Omitted if neither condition is met. Returned only when result.resultCode is SUCCESS.
        """
        return self.__hosted_invoice_url

    @hosted_invoice_url.setter
    def hosted_invoice_url(self, value):
        self.__hosted_invoice_url = value
    @property
    def period_start(self):
        """
        Billing period start timestamp (ISO 8601, e.g., &#x60;2026-03-01T00:00:00+00:00&#x60;). Cannot be null. Returned only when result.resultCode is SUCCESS.
        """
        return self.__period_start

    @period_start.setter
    def period_start(self, value):
        self.__period_start = value
    @property
    def period_end(self):
        """
        Billing period end timestamp (ISO 8601). Cannot be null. Returned only when result.resultCode is SUCCESS.
        """
        return self.__period_end

    @period_end.setter
    def period_end(self, value):
        self.__period_end = value
    @property
    def due_date(self):
        """
        Payment due date, format: &#x60;yyyy-MM-dd&#x60; (date-only, no time component). Cannot be null. Returned only when result.resultCode is SUCCESS.
        """
        return self.__due_date

    @due_date.setter
    def due_date(self, value):
        self.__due_date = value
    @property
    def paid_time(self):
        """
        Timestamp when the invoice was fully paid (ISO 8601). Omitted if unpaid. Returned only when result.resultCode is SUCCESS.
        """
        return self.__paid_time

    @paid_time.setter
    def paid_time(self, value):
        self.__paid_time = value
    @property
    def description(self):
        """
        Invoice-level description text displayed on the invoice. Note: line items carry their own &#x60;description&#x60; field (max 256) scoped to the individual line item. Omitted when not set. Returned only when result.resultCode is SUCCESS.
        """
        return self.__description

    @description.setter
    def description(self, value):
        self.__description = value
    @property
    def items(self):
        """
        Array of line items that make up this invoice. May be empty for invoices with only manual amounts. Cannot be null. Returned only when result.resultCode is SUCCESS.
        """
        return self.__items

    @items.setter
    def items(self, value):
        self.__items = value
    @property
    def payments(self):
        """
        Payment attempts for this invoice. Queried by merchantId and invoiceId. Omitted if no payment attempts exist. Returned only when result.resultCode is SUCCESS.
        """
        return self.__payments

    @payments.setter
    def payments(self, value):
        self.__payments = value
    @property
    def invoice_notes(self):
        """
        Array of notes attached to the invoice, sorted by time descending (most recent first). Each note captures contextual information about an action performed on the invoice (e.g., void, finalize, paid). Stored in the invoice metadata. Omitted if no notes exist for the invoice. Returned only when result.resultCode is SUCCESS.
        """
        return self.__invoice_notes

    @invoice_notes.setter
    def invoice_notes(self, value):
        self.__invoice_notes = value
    @property
    def gmt_create(self):
        """
        ISO 8601 timestamp of invoice creation (e.g., &#x60;2026-03-01T00:59:55+00:00&#x60;). Cannot be null. Returned only when result.resultCode is SUCCESS.
        """
        return self.__gmt_create

    @gmt_create.setter
    def gmt_create(self, value):
        self.__gmt_create = value
    @property
    def gmt_update(self):
        """
        ISO 8601 timestamp of last invoice update. Cannot be null. Returned only when result.resultCode is SUCCESS.
        """
        return self.__gmt_update

    @gmt_update.setter
    def gmt_update(self, value):
        self.__gmt_update = value
    @property
    def discounts(self):
        """
        Invoice-level discount items applied to this invoice. Each element carries either a &#x60;couponId&#x60; or &#x60;promotionCodeId&#x60;. Parsed from the invoice &#x60;discountItemIds&#x60; JSON column at query time. The computed total is reflected in &#x60;discountAmount&#x60;. Omitted if no discounts are applied. See DiscountItem Object below for field details. Returned only when result.resultCode is SUCCESS.
        """
        return self.__discounts

    @discounts.setter
    def discounts(self, value):
        self.__discounts = value
    @property
    def post_payment_credit_notes_amount(self):
        """Gets the post_payment_credit_notes_amount of this AlipayInvoiceInquireDetailsResponse.
        
        """
        return self.__post_payment_credit_notes_amount

    @post_payment_credit_notes_amount.setter
    def post_payment_credit_notes_amount(self, value):
        self.__post_payment_credit_notes_amount = value
    @property
    def pre_payment_credit_notes_amount(self):
        """Gets the pre_payment_credit_notes_amount of this AlipayInvoiceInquireDetailsResponse.
        
        """
        return self.__pre_payment_credit_notes_amount

    @pre_payment_credit_notes_amount.setter
    def pre_payment_credit_notes_amount(self, value):
        self.__pre_payment_credit_notes_amount = value
    @property
    def payment_deducted(self):
        """Gets the payment_deducted of this AlipayInvoiceInquireDetailsResponse.
        
        """
        return self.__payment_deducted

    @payment_deducted.setter
    def payment_deducted(self, value):
        self.__payment_deducted = value


    

    def to_ams_dict(self):
        params = dict()
        if hasattr(self, "result") and self.result is not None:
            params['result'] = self.result
        if hasattr(self, "invoice_id") and self.invoice_id is not None:
            params['invoiceId'] = self.invoice_id
        if hasattr(self, "invoice_request_id") and self.invoice_request_id is not None:
            params['invoiceRequestId'] = self.invoice_request_id
        if hasattr(self, "subscription_id") and self.subscription_id is not None:
            params['subscriptionId'] = self.subscription_id
        if hasattr(self, "customer_id") and self.customer_id is not None:
            params['customerId'] = self.customer_id
        if hasattr(self, "invoice_number") and self.invoice_number is not None:
            params['invoiceNumber'] = self.invoice_number
        if hasattr(self, "customer_first_name") and self.customer_first_name is not None:
            params['customerFirstName'] = self.customer_first_name
        if hasattr(self, "customer_last_name") and self.customer_last_name is not None:
            params['customerLastName'] = self.customer_last_name
        if hasattr(self, "customer_email") and self.customer_email is not None:
            params['customerEmail'] = self.customer_email
        if hasattr(self, "reason") and self.reason is not None:
            params['reason'] = self.reason
        if hasattr(self, "phase_no") and self.phase_no is not None:
            params['phaseNo'] = self.phase_no
        if hasattr(self, "status") and self.status is not None:
            params['status'] = self.status
        if hasattr(self, "currency") and self.currency is not None:
            params['currency'] = self.currency
        if hasattr(self, "subtotal") and self.subtotal is not None:
            params['subtotal'] = self.subtotal
        if hasattr(self, "discount_amount") and self.discount_amount is not None:
            params['discountAmount'] = self.discount_amount
        if hasattr(self, "total_amount") and self.total_amount is not None:
            params['totalAmount'] = self.total_amount
        if hasattr(self, "paid_amount") and self.paid_amount is not None:
            params['paidAmount'] = self.paid_amount
        if hasattr(self, "remain_amount") and self.remain_amount is not None:
            params['remainAmount'] = self.remain_amount
        if hasattr(self, "tax_amount") and self.tax_amount is not None:
            params['taxAmount'] = self.tax_amount
        if hasattr(self, "collection_method") and self.collection_method is not None:
            params['collectionMethod'] = self.collection_method
        if hasattr(self, "payment_method") and self.payment_method is not None:
            params['paymentMethod'] = self.payment_method
        if hasattr(self, "shipping") and self.shipping is not None:
            params['shipping'] = self.shipping
        if hasattr(self, "hosted_invoice_url") and self.hosted_invoice_url is not None:
            params['hostedInvoiceUrl'] = self.hosted_invoice_url
        if hasattr(self, "period_start") and self.period_start is not None:
            params['periodStart'] = self.period_start
        if hasattr(self, "period_end") and self.period_end is not None:
            params['periodEnd'] = self.period_end
        if hasattr(self, "due_date") and self.due_date is not None:
            params['dueDate'] = self.due_date
        if hasattr(self, "paid_time") and self.paid_time is not None:
            params['paidTime'] = self.paid_time
        if hasattr(self, "description") and self.description is not None:
            params['description'] = self.description
        if hasattr(self, "items") and self.items is not None:
            params['items'] = self.items
        if hasattr(self, "payments") and self.payments is not None:
            params['payments'] = self.payments
        if hasattr(self, "invoice_notes") and self.invoice_notes is not None:
            params['invoiceNotes'] = self.invoice_notes
        if hasattr(self, "gmt_create") and self.gmt_create is not None:
            params['gmtCreate'] = self.gmt_create
        if hasattr(self, "gmt_update") and self.gmt_update is not None:
            params['gmtUpdate'] = self.gmt_update
        if hasattr(self, "discounts") and self.discounts is not None:
            params['discounts'] = self.discounts
        if hasattr(self, "post_payment_credit_notes_amount") and self.post_payment_credit_notes_amount is not None:
            params['postPaymentCreditNotesAmount'] = self.post_payment_credit_notes_amount
        if hasattr(self, "pre_payment_credit_notes_amount") and self.pre_payment_credit_notes_amount is not None:
            params['prePaymentCreditNotesAmount'] = self.pre_payment_credit_notes_amount
        if hasattr(self, "payment_deducted") and self.payment_deducted is not None:
            params['paymentDeducted'] = self.payment_deducted
        return params


    def parse_rsp_body(self, response_body):
        response_body = super(AlipayInvoiceInquireDetailsResponse, self).parse_rsp_body(response_body)
        if 'result' in response_body:
            self.__result = Result()
            self.__result.parse_rsp_body(response_body['result'])
        if 'invoiceId' in response_body:
            self.__invoice_id = response_body['invoiceId']
        if 'invoiceRequestId' in response_body:
            self.__invoice_request_id = response_body['invoiceRequestId']
        if 'subscriptionId' in response_body:
            self.__subscription_id = response_body['subscriptionId']
        if 'customerId' in response_body:
            self.__customer_id = response_body['customerId']
        if 'invoiceNumber' in response_body:
            self.__invoice_number = response_body['invoiceNumber']
        if 'customerFirstName' in response_body:
            self.__customer_first_name = response_body['customerFirstName']
        if 'customerLastName' in response_body:
            self.__customer_last_name = response_body['customerLastName']
        if 'customerEmail' in response_body:
            self.__customer_email = response_body['customerEmail']
        if 'reason' in response_body:
            self.__reason = response_body['reason']
        if 'phaseNo' in response_body:
            self.__phase_no = response_body['phaseNo']
        if 'status' in response_body:
            self.__status = response_body['status']
        if 'currency' in response_body:
            self.__currency = response_body['currency']
        if 'subtotal' in response_body:
            self.__subtotal = Amount()
            self.__subtotal.parse_rsp_body(response_body['subtotal'])
        if 'discountAmount' in response_body:
            self.__discount_amount = Amount()
            self.__discount_amount.parse_rsp_body(response_body['discountAmount'])
        if 'totalAmount' in response_body:
            self.__total_amount = Amount()
            self.__total_amount.parse_rsp_body(response_body['totalAmount'])
        if 'paidAmount' in response_body:
            self.__paid_amount = Amount()
            self.__paid_amount.parse_rsp_body(response_body['paidAmount'])
        if 'remainAmount' in response_body:
            self.__remain_amount = Amount()
            self.__remain_amount.parse_rsp_body(response_body['remainAmount'])
        if 'taxAmount' in response_body:
            self.__tax_amount = Amount()
            self.__tax_amount.parse_rsp_body(response_body['taxAmount'])
        if 'collectionMethod' in response_body:
            self.__collection_method = response_body['collectionMethod']
        if 'paymentMethod' in response_body:
            self.__payment_method = PaymentMethod()
            self.__payment_method.parse_rsp_body(response_body['paymentMethod'])
        if 'shipping' in response_body:
            self.__shipping = InvoiceShipping()
            self.__shipping.parse_rsp_body(response_body['shipping'])
        if 'hostedInvoiceUrl' in response_body:
            self.__hosted_invoice_url = response_body['hostedInvoiceUrl']
        if 'periodStart' in response_body:
            self.__period_start = response_body['periodStart']
        if 'periodEnd' in response_body:
            self.__period_end = response_body['periodEnd']
        if 'dueDate' in response_body:
            self.__due_date = response_body['dueDate']
        if 'paidTime' in response_body:
            self.__paid_time = response_body['paidTime']
        if 'description' in response_body:
            self.__description = response_body['description']
        if 'items' in response_body:
            self.__items = []
            for item in response_body['items']:
                obj = InvoiceItem()
                obj.parse_rsp_body(item)
                self.__items.append(obj)
        if 'payments' in response_body:
            self.__payments = []
            for item in response_body['payments']:
                obj = InvoicePayment()
                obj.parse_rsp_body(item)
                self.__payments.append(obj)
        if 'invoiceNotes' in response_body:
            self.__invoice_notes = []
            for item in response_body['invoiceNotes']:
                obj = InvoiceNote()
                obj.parse_rsp_body(item)
                self.__invoice_notes.append(obj)
        if 'gmtCreate' in response_body:
            self.__gmt_create = response_body['gmtCreate']
        if 'gmtUpdate' in response_body:
            self.__gmt_update = response_body['gmtUpdate']
        if 'discounts' in response_body:
            self.__discounts = []
            for item in response_body['discounts']:
                obj = BillingDiscount()
                obj.parse_rsp_body(item)
                self.__discounts.append(obj)
        if 'postPaymentCreditNotesAmount' in response_body:
            self.__post_payment_credit_notes_amount = Amount()
            self.__post_payment_credit_notes_amount.parse_rsp_body(response_body['postPaymentCreditNotesAmount'])
        if 'prePaymentCreditNotesAmount' in response_body:
            self.__pre_payment_credit_notes_amount = Amount()
            self.__pre_payment_credit_notes_amount.parse_rsp_body(response_body['prePaymentCreditNotesAmount'])
        if 'paymentDeducted' in response_body:
            self.__payment_deducted = Amount()
            self.__payment_deducted.parse_rsp_body(response_body['paymentDeducted'])
